# Generated by Django 5.2.7 on 2025-11-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(choices=[('VW', 'Volkswagen'), ('FIAT', 'Fiat'), ('GM', 'General Motors'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota'), ('HYUNDAI', 'Hyundai')], max_length=50, verbose_name='Marca')),
                ('ano', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Aluguel')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Diária (R$)')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data Prevista de Devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data Real de Devolução')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('carro', models.ForeignKey(limit_choices_to={'disponivel': True}, on_delete=django.db.models.deletion.PROTECT, to='carros.carro', verbose_name='Carro Alugado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carros.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
            },
        ),
    ]
