# Generated by Django 5.2.7 on 2025-11-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Real de Devolução'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
